In [4]:
import numpy as np
from numpy import linalg as la

evalues, evectors = la.eig(np.array([[1,2,3],[2,3,4],[3,4,5]]))
print("Eigen Values:",evalues)
print("eigen Vectors:",evectors)

Eigen Values: [ 9.62347538e+00 -6.23475383e-01  5.06426348e-16]
eigen Vectors: [[-0.38508979 -0.82767094  0.40824829]
 [-0.55951021 -0.14241368 -0.81649658]
 [-0.73393063  0.54284358  0.40824829]]


In [7]:
from numpy import linalg as la

arr = np.array([[1,1,1,1],[2,2,2,2],[0,6,6,6],[8,0,5,5]],dtype=np.float32)
print("Array :",arr)
U,s,V = la.svd(arr,full_matrices=False)
print("Factors of the given array by SVD :")
print("\nU = ",U,"\ns = ",s,"\nV = ",V)

Array : [[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [0. 6. 6. 6.]
 [8. 0. 5. 5.]]
Factors of the given array by SVD :

U =  [[-1.4187919e-01 -1.0973688e-02  4.2396918e-01 -8.9442718e-01]
 [-2.8375837e-01 -2.1947376e-02  8.4793836e-01  4.4721359e-01]
 [-6.5596479e-01 -7.1626824e-01 -2.3805468e-01 -4.4408921e-16]
 [-6.8488079e-01  6.9739354e-01 -2.1114115e-01 -4.4408921e-16]] 
s =  [1.3788077e+01 7.1386232e+00 9.6383584e-01 6.3202687e-17] 
V =  [[-4.4882560e-01 -3.3689865e-01 -5.8525842e-01 -5.8525842e-01]
 [ 7.7385783e-01 -6.0970825e-01 -1.2124329e-01 -1.2124329e-01]
 [ 4.4687763e-01  7.1746439e-01 -3.7785265e-01 -3.7785265e-01]
 [-0.0000000e+00  5.9859117e-17  7.0710677e-01 -7.0710677e-01]]


In [8]:
matrix = []
x = int(input('Enter the size of the matrix:'))
for i in range(x):
    m = list(map(int,input(f"Enter the {i} row elements:").split()))
    if len(m) != x:
        print('Error')
    matrix.append(m)
print(matrix)
evalues, evectors = np.linalg.eig(matrix)
print("Eigen Values of the given matrix is:\n",evalues)
print("Eigen Vectorsof the given matrix is:\n",evectors)
print()
U,s,V = np.linalg.svd(matrix,full_matrices=False)
print("Factors of the given array by SVD :")
print("\nU = ",U,"\ns = ",s,"\nV = ",V)

Enter the size of the matrix:3
Enter the 0 row elements:1 2 3
Enter the 1 row elements:2 3 4
Enter the 2 row elements:3 4 5
[[1, 2, 3], [2, 3, 4], [3, 4, 5]]
Eigen Values of the given matrix is:
 [ 9.62347538e+00 -6.23475383e-01  5.06426348e-16]
Eigen Vectorsof the given matrix is:
 [[-0.38508979 -0.82767094  0.40824829]
 [-0.55951021 -0.14241368 -0.81649658]
 [-0.73393063  0.54284358  0.40824829]]

Factors of the given array by SVD :

U =  [[-0.38508979  0.82767094  0.40824829]
 [-0.55951021  0.14241368 -0.81649658]
 [-0.73393063 -0.54284358  0.40824829]] 
s =  [9.62347538e+00 6.23475383e-01 3.97943080e-16] 
V =  [[-0.38508979 -0.55951021 -0.73393063]
 [-0.82767094 -0.14241368  0.54284358]
 [ 0.40824829 -0.81649658  0.40824829]]


In [9]:
la.svd(matrix)

(array([[-0.38508979,  0.82767094,  0.40824829],
        [-0.55951021,  0.14241368, -0.81649658],
        [-0.73393063, -0.54284358,  0.40824829]]),
 array([9.62347538e+00, 6.23475383e-01, 3.97943080e-16]),
 array([[-0.38508979, -0.55951021, -0.73393063],
        [-0.82767094, -0.14241368,  0.54284358],
        [ 0.40824829, -0.81649658,  0.40824829]]))

In [ ]:
$ Finding the Eigen values and eigen vectors for the user given input $
